[package]
name = "trunkee"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.2.5"
winit = "0.27.5"
image = "0.24.5"
wgpu = "0.14"
glam = "0.22.0"
log = "0.4.17"
env_logger = "0.9.3"
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"